-- Seed de 71 productos de ejemplo. Generado por scripts/gen-seed.ts.
-- No editar a mano: cambiá src/niches/skincare/productos.ts y corré npm run gen-seed.

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('5d221906-39be-54cf-8a4b-a8451c1bc147', 'Espuma Facial Extra Suave Mousse Cleanser', 'Idraet', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['textura', 'deshidratacion'], 'nacional', true, 1, 23200, 'https://http2.mlstatic.com/D_Q_NP_2X_832048-MLA104005799796_012026-V.webp', 'https://meli.la/1SzLiDr', 'https://www.mercadolibre.com.ar/p/MLA21801426', 'MLA21801426', 'Mousse de limpieza suave: saca la mugre del día sin dejar la piel tirante.', 'Mañana y noche, sobre la cara húmeda.', '2026-09-05', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('bbab9cd3-0891-5ed1-95f2-4ece713b533b', 'Gel Limpiador Facial Espumoso 236 ml', 'CeraVe', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'normal'], array['acne', 'textura'], 'europeo', true, 3, 55620, 'https://http2.mlstatic.com/D_Q_NP_2X_831598-MLA48269275817_112021-V.webp', 'https://meli.la/2k4hF9V', 'https://www.mercadolibre.com.ar/p/MLA25800983', 'MLA25800983', 'Gel espumoso para piel grasa o mixta, con ceramidas para no romper la barrera.', 'Mañana y noche. Si te reseca, dejalo solo de noche.', '2026-09-05', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('df632bf0-55e0-5fa8-8515-a863341156e3', 'Low pH Good Morning Gel Cleanser 150 ml', 'COSRX', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'textura', 'deshidratacion'], 'coreano', true, 2, 37504, 'https://http2.mlstatic.com/D_Q_NP_2X_865672-MLU75328154403_032024-V.webp', 'https://meli.la/2m5jdnL', 'https://www.mercadolibre.com.ar/p/MLA11139349', 'MLA11139349', 'Limpiador de pH bajo: respeta el manto ácido de la piel, por eso cae bien a la mañana.', 'Mañana y noche sobre la cara húmeda, poca cantidad.', '2026-09-05', 3, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('9f11e96c-a0d6-595c-836b-e2b01e5777d3', 'Centella Cleansing Foam 150 ml', 'Mixsoon', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'textura', 'deshidratacion'], 'coreano', true, 2, 38399, 'https://http2.mlstatic.com/D_Q_NP_2X_838019-MLA93483193946_102025-V.webp', 'https://meli.la/2s4tZod', 'https://www.mercadolibre.com.ar/p/MLAU3453545171', 'MLAU3453545171', 'Espuma con centella, pensada para limpiar sin dejar la piel chirriando.', 'Mañana y noche sobre la cara húmeda.', '2026-09-05', 3, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('bcf4f350-f721-51a5-b88d-88215ae1673e', 'Centella Ampoule Foam 125 ml', 'Skin1004', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'textura', 'deshidratacion'], 'coreano', true, 2, 36719, 'https://http2.mlstatic.com/D_Q_NP_2X_743990-MLA108176636618_032026-V.webp', 'https://meli.la/2woLVoE', 'https://www.mercadolibre.com.ar/p/MLA47129399', 'MLA47129399', 'Espuma de centella asiática. Limpia parejo y le va bien a casi cualquier piel.', 'Mañana y noche sobre la cara húmeda, enjuagá con agua.', '2026-09-05', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('5287ad8a-fb88-5094-a48f-51c710cd96ce', 'Cleanex Free Gel Limpiador 150 g', 'Cleanex', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'sensible'], array['acne', 'textura'], 'nacional', true, 2, 40162, 'https://http2.mlstatic.com/D_Q_NP_2X_716982-MLU72122769372_102023-V.webp', 'https://meli.la/1PTw6U7', 'https://www.mercadolibre.com.ar/p/MLA27603374', 'MLA27603374', 'Gel de limpieza sin jabón, formulado para piel sensible que además hace grasitud.', 'Mañana y noche. Enjuagá bien.', '2026-09-05', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('faafd241-6fe8-56a8-a766-ccdb6164db56', 'Ginseng Cleansing Oil Desmaquillante', 'Beauty of Joseon', 'limpiador_oleoso', 1, 'pm', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'textura', 'deshidratacion'], 'coreano', true, 2, 54739, 'https://http2.mlstatic.com/D_Q_NP_2X_965384-MLU78057625931_072024-V.webp', 'https://meli.la/2PwoAd6', 'https://www.mercadolibre.com.ar/p/MLA37240248', 'MLA37240248', 'Primer paso de la doble limpieza: el aceite saca protector solar y maquillaje que el agua sola no levanta.', 'De noche, sobre la cara SECA. Masajeá, mojate las manos para emulsionar y enjuagá. Después va el limpiador.', '2026-09-05', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('1f69f11c-96bc-5e0d-b79b-684a56278a28', 'Revitalift Glass Skin Crema 50 g', 'L''Oreal Paris', 'hidratante', 7, 'ambos', array['mixta', 'normal', 'seca'], array['textura', 'deshidratacion'], 'europeo', false, 2, 46477, 'https://http2.mlstatic.com/D_Q_NP_2X_678886-MLA106918493109_022026-V.webp', 'https://meli.la/1XvJrXG', 'https://www.mercadolibre.com.ar/p/MLA65451035', 'MLA65451035', 'Hidratante de textura liviana que deja la piel con aspecto pulido.', 'Después de limpiar, mañana y noche.', '2026-09-05', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('599f5ffc-515b-53e3-b1a9-6fa7f105cc0c', 'Tea-trica B5 Crema Facial 75 ml', 'Skin1004', 'hidratante', 7, 'ambos', array['grasa', 'mixta'], array['acne', 'textura'], 'coreano', true, 2, 45475, 'https://http2.mlstatic.com/D_Q_NP_2X_994827-MLU76998762803_062024-V.webp', 'https://meli.la/2HagYva', 'https://www.mercadolibre.com.ar/p/MLA37722163', 'MLA37722163', 'Hidratante con B5 pensada para piel oleosa y acneica: hidrata sin sensación pesada.', 'Después de limpiar, mañana y noche.', '2026-09-05', 5, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('6b7300c1-a37c-5810-a06b-a114171cc45f', 'Toleriane Dermallergo Crema 40 ml', 'La Roche-Posay', 'hidratante', 7, 'ambos', array['seca', 'sensible'], array['deshidratacion', 'textura'], 'europeo', true, 3, 114414, 'https://http2.mlstatic.com/D_Q_NP_2X_785042-MLU75601430788_042024-V.webp', 'https://meli.la/1gTzEb6', 'https://www.mercadolibre.com.ar/p/MLA19866311', 'MLA19866311', 'Formulada para piel reactiva: mínimo de ingredientes, sin fragancia.', 'Después de limpiar, mañana y noche.', '2026-09-05', 5, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('0385d1a3-9ab2-5343-9184-2abbd7a5502e', 'Dynasty Cream 50 ml', 'Beauty of Joseon', 'hidratante', 7, 'ambos', array['normal', 'seca'], array['deshidratacion', 'textura'], 'coreano', true, 3, 77299, 'https://http2.mlstatic.com/D_Q_NP_2X_914805-MLU75324226927_032024-V.webp', 'https://meli.la/2LMiAbi', 'https://www.mercadolibre.com.ar/p/MLA21179266', 'MLA21179266', 'Crema nutritiva para piel que tira. Más rica que una gel-crema.', 'Después de limpiar, mañana y noche.', '2026-09-05', 5, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('cae68c7d-d0d5-569c-97c1-dc7685e0fc83', 'Hyaluronic 4D Face Cream', 'Lidherma', 'hidratante', 7, 'ambos', array['mixta', 'normal', 'seca'], array['deshidratacion'], 'nacional', true, 1, 31573, 'https://http2.mlstatic.com/D_Q_NP_2X_751116-MLA51443088672_092022-V.webp', 'https://meli.la/2KUmRn1', 'https://www.mercadolibre.com.ar/p/MLA19474747', 'MLA19474747', 'Hidratación con hialurónico a precio nacional. Textura liviana.', 'Después de limpiar, mañana y noche.', '2026-09-05', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('a35fb8ba-c2f2-5e6f-94fa-2e96744d3fdc', 'Advanced Snail All In One Cream 50 ml', 'COSRX', 'hidratante', 7, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'manchas', 'textura', 'deshidratacion'], 'coreano', true, 1, 32999, 'https://http2.mlstatic.com/D_Q_NP_2X_843019-MLA115354367281_072026-V.webp', 'https://meli.la/2341vy4', 'https://www.mercadolibre.com.ar/up/MLAU3849329943', 'MLAU3849329943', 'Mucina de caracol: hidrata y ayuda a que las marcas se vayan emparejando. Muy versátil.', 'Después de limpiar, mañana y noche.', '2026-09-05', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('3043ace8-c198-5554-a4ef-4b3e0248ff31', 'Crema Hidratante de Dia FPS 30 50 g', 'Dermaglos', 'protector_solar', 4, 'am', array['mixta', 'normal', 'seca'], array['deshidratacion', 'manchas'], 'nacional', false, 1, 32661, 'https://http2.mlstatic.com/D_Q_NP_2X_695563-MLU72756171168_112023-V.webp', 'https://meli.la/2kbgQEt', 'https://www.mercadolibre.com.ar/p/MLA24692733', 'MLA24692733', 'Hidrata y protege en un solo paso. La opción para el que no va a hacer dos.', 'A la mañana, como último paso. Es FPS 30: alcanza para el día a día, pero si vas a estar horas al sol conviene uno de 50.', '2026-09-05', 2, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('ef88803e-f240-5ac9-a0c7-6dc45023f5cb', 'Protector Solar Rice + Probioticos SPF50+', 'Beauty of Joseon', 'protector_solar', 8, 'am', array['mixta', 'normal', 'seca', 'sensible'], array['manchas', 'textura', 'deshidratacion'], 'coreano', true, 2, 51999, 'https://http2.mlstatic.com/D_Q_NP_2X_957567-MLA94539763645_102025-V.webp', 'https://meli.la/1B2LZaE', 'https://www.mercadolibre.com.ar/p/MLAU3480823224', 'MLAU3480823224', 'Filtro coreano de textura liviana, no deja blanco ni sensación pegajosa.', 'Último paso de la mañana, todos los días.', '2026-09-05', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('2b09ab2e-48f4-5490-860e-b01d8e980e4f', 'Fusion Water Magic SPF 50', 'ISDIN', 'protector_solar', 8, 'am', array['grasa', 'mixta', 'normal'], array['acne', 'manchas'], 'europeo', false, 3, 55904, 'https://http2.mlstatic.com/D_Q_NP_2X_711953-MLA99930410153_112025-V.webp', 'https://meli.la/1Zv7ivK', 'https://www.mercadolibre.com.ar/p/MLA26916726', 'MLA26916726', 'Textura agua, se absorbe rápido. Un clásico para piel que brilla.', 'Último paso de la mañana. Reponé cada 3-4 hs si estás al sol.', '2026-09-05', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('243c3ca9-7456-5c5f-adae-56bc432fdc4c', 'Ultra-light Invisible Sunscreen SPF 50 PA++++ 50 ml', 'COSRX', 'protector_solar', 8, 'am', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'manchas', 'textura', 'deshidratacion'], 'coreano', true, 2, 42299, 'https://http2.mlstatic.com/D_Q_NP_2X_729825-MLA107254048819_022026-V.webp', 'https://meli.la/1mZvXGj', 'https://www.mercadolibre.com.ar/p/MLA2097460920', 'MLA2097460920', 'Muy liviano e invisible. Es el más fácil de usar todos los días sin renegar.', 'Último paso de la mañana, todos los días.', '2026-09-05', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('ee65576a-883b-5b68-82d9-b06c4540f9cc', 'Sun Oil Control Toque Seco FPS 50 50 ml', 'Eucerin', 'protector_solar', 8, 'am', array['grasa', 'mixta'], array['acne'], 'europeo', false, 2, 53206, 'https://http2.mlstatic.com/D_Q_NP_2X_967739-MLA117137014457_092026-V.webp', 'https://meli.la/2Vgkwfh', 'https://www.mercadolibre.com.ar/p/MLA16048275', 'MLA16048275', 'Acabado seco de verdad: control de brillo para piel muy oleosa.', 'Último paso de la mañana.', '2026-09-05', 5, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('49a08f9d-4ffe-54a6-ae25-cb54ece5198f', 'Hyalu-Cica Water-Fit Sun Serum SPF50+ 50 ml', 'Skin1004', 'protector_solar', 8, 'am', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'textura', 'deshidratacion'], 'coreano', true, 2, 54000, 'https://http2.mlstatic.com/D_Q_NP_2X_614355-MLA99834144935_112025-V.webp', 'https://meli.la/1Le23Cy', 'https://www.mercadolibre.com.ar/p/MLA24454808', 'MLA24454808', 'Protector con textura de serum. Se siente como un paso de skincare, no como pantalla solar.', 'Último paso de la mañana, todos los días.', '2026-09-05', 3, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('1782a74e-046f-572d-b361-27dacdf2b3ea', 'Fusion Water Magic Color Light SPF 50 50 ml', 'ISDIN', 'protector_solar', 8, 'am', array['grasa', 'mixta', 'normal'], array['manchas', 'textura'], 'europeo', false, 2, 52980, 'https://http2.mlstatic.com/D_Q_NP_2X_611145-MLA99918803569_112025-V.webp', 'https://meli.la/1YCbeGw', 'https://www.mercadolibre.com.ar/p/MLA20067103', 'MLA20067103', 'Igual que el Fusion Water pero con color: empareja el tono y reemplaza la base liviana.', 'Último paso de la mañana.', '2026-09-05', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('5540f526-7bbb-587e-9340-4c367d3fecb5', 'Protector Solar Facial Control Anti-Brillo FPS 50 50 ml', 'NIVEA', 'protector_solar', 8, 'am', array['grasa', 'mixta'], array['acne'], 'europeo', false, 1, 15488, 'https://http2.mlstatic.com/D_Q_NP_2X_788259-MLA117198265649_092026-V.webp', 'https://meli.la/2DuYPWN', 'https://www.mercadolibre.com.ar/p/MLA16189493', 'MLA16189493', 'La opción más barata de la lista para cumplir con el paso que más importa.', 'Último paso de la mañana, todos los días.', '2026-09-05', 5, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('eca1e945-2ceb-5a4b-8d53-5afe77870730', 'Serum Anti Manchas Vitamina C 30 ml', 'Garnier', 'serum_activo', 2, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['manchas', 'textura'], 'europeo', false, 1, 24693, 'https://http2.mlstatic.com/D_Q_NP_2X_984767-MLA114537078502_082026-V.webp', 'https://meli.la/2cvShSS', 'https://www.mercadolibre.com.ar/p/MLA18957818', 'MLA18957818', 'Vitamina C accesible para trabajar sobre manchas y marcas.', 'Después de limpiar y antes de la crema. Rinde más a la mañana, bajo el protector. Empezá día por medio.', '2026-09-05', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('2e00ac05-c649-5f6d-bfd2-cce864f2e80e', 'Niacinamida 10% + Zinc 1% 30 ml', 'The Ordinary', 'serum_activo', 4, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'manchas', 'textura'], 'europeo', true, 2, 39999, 'https://http2.mlstatic.com/D_Q_NP_2X_670477-MLU69223240175_052023-V.webp', 'https://meli.la/1UsymVj', 'https://www.mercadolibre.com.ar/p/MLA23033385', 'MLA23033385', 'Equilibra el brillo y ayuda con poros y marcas. El activo más fácil para arrancar.', 'Unas gotas antes de la crema, mañana o noche.', '2026-09-05', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('9f280ac4-84cb-5eca-b3cd-583eceef3219', 'Mineral 89 Contorno de Ojos 15 ml', 'Vichy', 'contorno', 6, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['deshidratacion', 'textura'], 'europeo', true, 2, 47977, 'https://http2.mlstatic.com/D_Q_NP_2X_623415-MLU78028761401_072024-V.webp', 'https://meli.la/1GnukDr', 'https://www.mercadolibre.com.ar/p/MLA18956630', 'MLA18956630', 'Contorno liviano con ácido hialurónico. Apto para todo tipo de piel.', 'Golpecitos suaves alrededor del ojo, mañana y noche.', '2026-09-05', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('360306d6-7439-53f6-80d0-9d8644884868', 'Milk Skin Toner 150 ml', 'TIRTIR', 'tonico', 3, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['deshidratacion', 'textura'], 'coreano', true, 3, 65999, 'https://http2.mlstatic.com/D_Q_NP_2X_909856-MLA94560758043_102025-V.webp', 'https://meli.la/27hmLZT', 'https://www.mercadolibre.com.ar/up/MLAU3481553718', 'MLAU3481553718', 'Tónico de textura lechosa. Suma humedad sin peso y deja la piel lista para lo que viene después.', 'Después de limpiar, con las manos o un algodón. Mañana y noche.', '2026-09-05', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('ed3e0a91-2640-59fc-80d5-5008a15d65a5', 'Tónico Exfoliante de Ácido Glicólico 7 por ciento 100 ml', 'The Ordinary', 'exfoliante', 9, 'pm', array['grasa', 'mixta', 'normal'], array['textura', 'manchas'], 'europeo', false, 3, 57170, 'https://http2.mlstatic.com/D_Q_NP_2X_641467-MLU74154671501_012024-V.webp', 'https://meli.la/2cHLcue', 'https://www.mercadolibre.com.ar/p/MLA29493655', 'MLA29493655', 'Ácido glicólico al 7 por ciento: empareja la textura y ayuda a que las marcas se aclaren.', 'De noche, sobre la piel seca, 2 o 3 veces por semana. Nunca el mismo día que otro ácido.', '2026-09-05', 4, true, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('d47c5c7f-88f8-5547-8ee2-440abda55985', 'Avene Hydrance Spf30 Crema Facial Hidratante Piel Sensible', 'Avène', 'hidratante', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array[], 'europeo', true, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_797988-MLA110062280061_042026-V.webp', 'https://meli.la/2qCihSr', 'https://www.mercadolibre.com.ar/p/MLA67629151', 'MLA67629151', 'Hidratante con FPS 30 para piel sensible: cubre dos pasos cuando la rutina tiene que ser corta.', 'A la mañana, como último paso. Si vas a estar horas al sol, mejor un protector de 50 aparte.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('6fe42157-e35e-5446-a929-217b76a0eb49', 'Avene Tolerance Control Crema Apaisante Restauradora X 40 Tipo de piel Sensible', 'Avène', 'hidratante', 0, 'ambos', array['mixta', 'normal', 'seca', 'sensible'], array['deshidratacion'], 'europeo', true, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_994229-MLU74192405269_012024-V.webp', 'https://meli.la/1LRTaMn', 'https://www.mercadolibre.com.ar/p/MLA23143346', 'MLA23143346', 'Catorce ingredientes y ninguno de más. Es la fórmula más corta del catálogo, pensada para piel que reacciona a casi todo.', 'Mañana y noche. Si tenés la piel irritada, usala sola unos días antes de volver a sumar activos.', '2026-09-09', 5, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('0dd6a780-c079-5225-a8ba-abf771937d09', 'Crema Facial Isdin Ureadin Fusion Melting Cream 50ml - Piel Normal', 'ISDIN', 'hidratante', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['textura', 'deshidratacion', 'manchas'], 'europeo', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_896103-MLA79442841694_102024-V.webp', 'https://meli.la/1D8LvKN', 'https://www.mercadolibre.com.ar/p/MLA21174873', 'MLA21174873', 'Urea y ácido láctico para suavizar la textura, con ceramidas que reponen lo que la exfoliación se lleva.', 'De noche, sobre la piel limpia. Trae fragancia: si tu piel reacciona, probala primero en el cuello.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('786825f8-fa3a-5ae3-9a12-3514acff04d9', 'Crema Gel Hidratante Anti-imperfecciones Garnier 50ml', 'Garnier', 'hidratante', 0, 'ambos', array['grasa', 'mixta', 'normal'], array['manchas', 'deshidratacion', 'acne', 'textura'], 'europeo', false, 1, null, 'https://http2.mlstatic.com/D_Q_NP_2X_600216-MLU75324413628_032024-V.webp', 'https://meli.la/2JZyLDC', 'https://www.mercadolibre.com.ar/p/MLA35115621', 'MLA35115621', 'Gel liviano con niacinamida y salicílico: hidrata sin cargar y trabaja sobre los granitos al mismo tiempo.', 'Mañana y noche. Lleva alcohol, así que si tenés la piel seca o tirante conviene otra.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('808e43ee-9a93-5cf2-ae71-8210102219b0', 'Crema Hidratante Eucerin Aquaporin Active para piel mixta-normal de 50mL', 'Eucerin', 'hidratante', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['deshidratacion'], 'europeo', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_719542-MLA84839455147_052025-V.webp', 'https://meli.la/1M3qgpD', 'https://www.mercadolibre.com.ar/p/MLA9210936', 'MLA9210936', 'Su activo no atrae agua: estimula los canales por los que el agua circula entre las células. Es un mecanismo distinto al del resto del catálogo.', 'Mañana y noche, sobre la piel limpia.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('df0d5355-4ed9-5030-953a-4a710c56fd04', 'Recarga Crema Hidratante Facial Neutrogena Hydro Boost 50 GR', 'Neutrogena', 'hidratante', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['deshidratacion'], 'europeo', false, 1, null, 'https://http2.mlstatic.com/D_Q_NP_2X_910480-MLU73044464102_112023-V.webp', 'https://meli.la/31Dwh9j', 'https://www.mercadolibre.com.ar/p/MLA28531465', 'MLA28531465', 'El gel de hialurónico de siempre, en formato recarga: mismo producto, menos plástico y menos plata.', 'Mañana y noche. Sobre la piel todavía húmeda rinde más.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('d0d3332a-fc59-5b58-96c8-77f6fb8eabde', 'Eucerin Hyaluron - Filler Día Piel Normal a Mixta Fps15 X 50m', 'Eucerin', 'hidratante', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['manchas', 'deshidratacion'], 'europeo', false, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_647940-MLA115522698291_082026-V.webp', 'https://meli.la/2QfMmn6', 'https://www.mercadolibre.com.ar/p/MLA9855881', 'MLA9855881', 'Hidratante de día con hialurónico. El FPS 15 es un extra, no reemplaza al protector solar.', 'A la mañana. Si vas a estar al sol, ponete un protector de 50 encima.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('9e56836d-95e8-5f74-b707-65927d4d01c0', 'Gel Crema Hidratante Facial Piel Sensible Seca - Mixta Aveno 50g', 'Aveno', 'hidratante', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['deshidratacion'], 'nacional', true, 1, null, 'https://http2.mlstatic.com/D_Q_NP_2X_608024-MLU74023179806_012024-V.webp', 'https://meli.la/2buZJKi', 'https://www.mercadolibre.com.ar/p/MLA22990183', 'MLA22990183', 'Avena coloidal, que es de los calmantes con más respaldo, en una textura gel que no pesa.', 'Mañana y noche. Va bien incluso cuando la piel está reactiva.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('353d07b5-d81e-5866-8a98-4e8801e5fd0a', 'La Roche-Posay Effaclar Mat 40 mL', 'La Roche-Posay', 'hidratante', 0, 'ambos', array['grasa', 'mixta', 'normal'], array['acne', 'textura'], 'europeo', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_733246-MLU72700362139_112023-V.webp', 'https://meli.la/2PQYHsi', 'https://www.mercadolibre.com.ar/p/MLA9196384', 'MLA9196384', 'Matifica y trabaja el poro con LHA, que es la versión lenta del salicílico: descama de a poco en vez de golpe.', 'Mañana y noche. Está pensada para piel grasa: si tenés la piel seca te va a tirar.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('3b6b8c59-405a-5357-b92f-37f1e9ee58bc', 'Agua Micelar Anti-imperfecciones Con Ácido Salicílico Garnier 400ml', 'Garnier', 'limpiador', 0, 'ambos', array['grasa', 'mixta', 'normal'], array['acne', 'textura', 'manchas'], 'europeo', false, 1, null, 'https://http2.mlstatic.com/D_Q_NP_2X_608460-MLU77411990239_072024-V.webp', 'https://meli.la/22GvuCY', 'https://www.mercadolibre.com.ar/p/MLA24300545', 'MLA24300545', 'Agua micelar con salicílico: saca el maquillaje y de paso trabaja sobre los granitos.', 'Con un algodón, antes del limpiador. No hace falta enjuagar, pero si te tira, enjuagá.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('8fe63985-3796-5e78-9de6-de0a82281a49', 'Agua Micelar Todo en 1 Garnier 400ml', 'Garnier', 'limpiador', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array[], 'europeo', true, 1, null, 'https://http2.mlstatic.com/D_Q_NP_2X_769959-MLA103725782735_012026-V.webp', 'https://meli.la/2EeBV4a', 'https://www.mercadolibre.com.ar/p/MLA20546060', 'MLA20546060', 'Agua micelar sin activos: saca maquillaje y protector solar sin frotar.', 'Con un algodón, como primer paso de la noche. Después, el limpiador.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('52747e64-8f8a-5be8-b935-6ef7e5ad517b', 'Cerave Gel Limpiador Espumoso', 'CeraVe', 'limpiador', 0, 'ambos', array['grasa', 'mixta', 'normal', 'sensible'], array['deshidratacion', 'manchas'], 'europeo', true, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_831598-MLA48269275817_112021-V.webp', 'https://meli.la/1rfMXV1', 'https://www.mercadolibre.com.ar/up/MLAU141343879', 'MLAU141343879', 'Trae el set completo de la barrera —ceramidas, colesterol y fitoesfingosina—, que es justo lo que un limpiador suele llevarse.', 'Mañana y noche sobre la cara húmeda. Sin fragancia.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('2de5e9f9-c212-5e1d-9828-d90c7aff3de9', 'Eucerin Dermopure Oil Control Gel Limpiador Facial 400ml', 'Eucerin', 'limpiador', 0, 'ambos', array['grasa', 'mixta', 'normal'], array['acne', 'textura'], 'europeo', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_828046-MLA115386148199_072026-V.webp', 'https://meli.la/2mjSuZ3', 'https://www.mercadolibre.com.ar/p/MLA37349507', 'MLA37349507', 'Gel con salicílico para piel que hace grasitud. Se enjuaga rápido, así que el ácido actúa poco: limpia, y no mucho más.', 'Mañana y noche. Si te deja la piel chirriando, bajá a una vez por día.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('069e085b-93f0-5e5e-a907-a409f3e4f8d9', 'Gel Limpiador Crema Hidratante Anti Imperfecciones Garnier 250ml', 'Garnier', 'limpiador', 0, 'ambos', array['grasa', 'mixta', 'normal'], array['manchas', 'deshidratacion', 'acne', 'textura'], 'europeo', false, 1, null, 'https://http2.mlstatic.com/D_Q_NP_2X_773271-MLA83522206951_042025-V.webp', 'https://meli.la/2hh95rn', 'https://www.mercadolibre.com.ar/p/MLA47671534', 'MLA47671534', 'Limpia y deja niacinamida y salicílico en el paso donde casi nadie los pone.', 'Mañana y noche sobre la cara húmeda.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('7787bab2-6a2e-5aae-be68-d587cba8588e', 'Gel limpiador hidratante Neutrogena Hydro Boost, 150 ml, para todo tipo de piel', 'Neutrogena', 'limpiador', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['deshidratacion'], 'europeo', true, 1, null, 'https://http2.mlstatic.com/D_Q_NP_2X_755602-MLA90129505693_082025-V.webp', 'https://meli.la/1C7GjFA', 'https://www.mercadolibre.com.ar/p/MLA53897352', 'MLA53897352', 'Limpia sin activos y sin dejar la piel tirante. Cuando la rutina ya tiene bastante, el limpiador es el lugar para no sumar nada.', 'Mañana y noche sobre la cara húmeda.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('5c1c9584-f216-5825-abea-fdcaca926992', 'La Roche-Posay Lipikar Syndet Ap+ Gel Limpiador X 200 Ml', 'La Roche-Posay', 'limpiador', 0, 'ambos', array['mixta', 'normal', 'seca', 'sensible'], array['manchas', 'deshidratacion'], 'europeo', true, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_946672-MLA81335047993_122024-V.webp', 'https://meli.la/1fEFWNk', 'https://www.mercadolibre.com.ar/up/MLAU376385300', 'MLAU376385300', 'Syndet sin jabón, con karité y niacinamida. Está formulado para piel atópica, que es el estándar más exigente de suavidad.', 'Mañana y noche, o sólo de noche si tenés la piel muy seca. Sin fragancia.', '2026-09-09', 5, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('677a05dc-1afc-5840-8b42-4a09c03ee1cd', 'Limpiador en Gel Beauty Of Joseon Ciruela Verde 100ml Piel Grasa', 'Beauty of Joseon', 'limpiador', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array[], 'coreano', true, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_674444-MLU75478763708_042024-V.webp', 'https://meli.la/2enTXSc', 'https://www.mercadolibre.com.ar/p/MLA35427636', 'MLA35427636', 'Gel de limpieza coreano con tensioactivos suaves: saca la grasitud del día sin dejar la cara chirriando.', 'Mañana y noche sobre la cara húmeda.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('4be59db9-22f1-56c6-9ffe-21301474f42c', 'Limpiador Facial y Corporal Restaurador de la Piel Cetaphil Pro Ad Restoraderm para Pieles Atópicas', 'Cetaphil', 'limpiador', 0, 'ambos', array['mixta', 'normal', 'seca', 'sensible'], array['manchas', 'deshidratacion'], 'europeo', true, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_808512-MLA117318373787_092026-V.webp', 'https://meli.la/2XbQBQ8', 'https://www.mercadolibre.com.ar/p/MLA20030752', 'MLA20030752', 'Para piel atópica: limpia con muy poco tensioactivo y repone parte de lo que se lleva. Sirve para cara y cuerpo.', 'Mañana y noche. Sin fragancia.', '2026-09-09', 5, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('8293ef2d-878f-5dc7-85df-5254c10d8812', 'Limpiador Hidratante Cerave Piel Normal A Seca X 236ml', 'CeraVe', 'limpiador', 0, 'ambos', array['mixta', 'normal', 'seca', 'sensible'], array['deshidratacion'], 'europeo', true, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_801309-MLU76690984634_062024-V.webp', 'https://meli.la/17jJUUD', 'https://www.mercadolibre.com.ar/p/MLA37598876', 'MLA37598876', 'Limpiador cremoso con el set completo de ceramidas. Para piel seca, que es donde un gel espumoso suele pasarse.', 'De noche siempre; a la mañana sólo si tu piel lo pide. Sin fragancia.', '2026-09-09', 5, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('0cd46bf5-012f-5327-a946-2f0f6fdce296', 'Eucerin Sun Oil Control Protector Solar Facial Tono medio FPS 50 x 50 ml', 'Eucerin', 'protector_solar', 0, 'am', array['grasa', 'mixta', 'normal'], array['manchas', 'deshidratacion'], 'europeo', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_762558-MLA114257666624_082026-V.webp', 'https://meli.la/1xyAzGu', 'https://www.mercadolibre.com.ar/p/MLA19504960', 'MLA19504960', 'El color no es sólo estética: los óxidos de hierro son de lo poco que frena la luz visible, y la luz visible dispara las manchas.', 'A la mañana, último paso y en cantidad generosa. Lleva alcohol: si tenés la piel seca, buscá otro.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('093dc761-466b-5ac6-a91d-00f5fe2a9e32', 'Protector Solar Anthelios Oil Control Fps50+ 50 Ml', 'La Roche-Posay', 'protector_solar', 0, 'am', array['grasa', 'mixta', 'normal'], array['manchas'], 'europeo', false, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_782186-MLA103884345361_012026-V.webp', 'https://meli.la/1pVjW5o', 'https://www.mercadolibre.com.ar/up/MLAU3133622625', 'MLAU3133622625', 'Cubre hasta 400 nm, la franja de UVA que casi ningún protector alcanza y la que más pigmenta. Y además trae color.', 'A la mañana, último paso. Dos dedos alcanzan para toda la cara.', '2026-09-09', 5, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('f2c98169-24cf-59e5-8ceb-eebd40f7720c', 'La Roche-Posay Anthelios Fps50 Ultra Fluido Con Color X 50 Ml', 'La Roche-Posay', 'protector_solar', 0, 'am', array['grasa', 'mixta', 'normal'], array['manchas', 'acne'], 'europeo', false, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_928224-MLA99425629508_112025-V.webp', 'https://meli.la/2i65yF5', 'https://www.mercadolibre.com.ar/p/MLA16048263', 'MLA16048263', 'El único del catálogo que suma dióxido de titanio como filtro, no sólo como color. Fórmula mixta, para quien no se lleva bien con los filtros orgánicos solos.', 'A la mañana, último paso. Lleva alcohol denat, así que no es para piel muy seca.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('5d60fad9-e033-5346-8f50-790dc29d6f3a', 'Protector solar La Roche-Posay Anthelios UVMUNE 400 50FPS en crema 50mL con COLOR', 'La Roche-Posay', 'protector_solar', 0, 'am', array['grasa', 'mixta', 'normal', 'seca'], array['manchas'], 'europeo', false, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_772864-MLA99823835965_112025-V.webp', 'https://meli.la/2AgbA84', 'https://www.mercadolibre.com.ar/p/MLA58897902', 'MLA58897902', 'Filtro hasta 400 nm más color: para manchas es la combinación más completa que tenemos.', 'A la mañana, último paso y en cantidad generosa. Reponé si vas a estar muchas horas afuera.', '2026-09-09', 5, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('d56c81d0-185e-5694-8352-fb09eaf5cd27', 'Garnier Protector Solar Super Uv Fluido Invisible Fps50 40 Ml', null, 'protector_solar', 0, 'am', array['grasa', 'mixta', 'normal'], array['manchas', 'deshidratacion', 'acne', 'textura'], 'europeo', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_870195-MLA99826299497_112025-V.webp', 'https://meli.la/2Arth2T', 'https://www.mercadolibre.com.ar/p/MLA38098313', 'MLA38098313', 'Protector con niacinamida y salicílico adentro. Es poco común, y buena idea si tenés piel grasa y no querés sumar otro frasco.', 'A la mañana, último paso. Si ya usás un sérum con salicílico, con uno de los dos alcanza.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('463f3803-17e2-566e-8226-254fe7546889', 'Crema Retinol Boost Anti-arrugas Neutrogena 30ml Todo Tipo De Piel Día-noche', 'Neutrogena', 'retinoide', 0, 'pm', array['grasa', 'mixta', 'normal', 'seca'], array['textura', 'deshidratacion'], 'europeo', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_752112-MLA93525041448_102025-V.webp', 'https://meli.la/2zvq95Y', 'https://www.mercadolibre.com.ar/p/MLA58622882', 'MLA58622882', 'Retinol en crema, con bisabolol para amortiguar. Es el activo con más respaldo para arrugas y textura.', 'De noche, sobre la piel seca. Dos veces por semana las primeras dos semanas, después subí. Protector solar al día siguiente, sin excepción.', '2026-09-09', 4, true, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('07628bc3-918c-5cca-a643-60ef9be1a864', 'Eximia Hyalu-r Concentre Serum Antiedad X 15 Ml', 'Eximia', 'retinoide', 0, 'pm', array['grasa', 'mixta', 'normal', 'seca'], array['textura', 'manchas', 'deshidratacion'], 'nacional', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_744195-MLA108423450143_032026-V.webp', 'https://meli.la/2XtPwss', 'https://www.mercadolibre.com.ar/p/MLA20021768', 'MLA20021768', 'Retinol acompañado de niacinamida, que es lo que hace que se tolere: menos descamación y más chance de sostenerlo.', 'De noche, sobre la piel seca, empezando dos veces por semana. Nunca la misma noche que un exfoliante.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('24fe4638-63d5-5fd1-8e2d-07c15ffabda3', 'La Roche Posay Retinol B3 Sérum Regenerador X 30 Ml Todo Tipo De Piel, Incluso Sensible.', 'La Roche-Posay', 'retinoide', 0, 'pm', array['grasa', 'mixta', 'normal', 'seca'], array['textura', 'manchas', 'deshidratacion'], 'europeo', false, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_780551-MLA92849421969_092025-V.webp', 'https://meli.la/2b8ob3n', 'https://www.mercadolibre.com.ar/up/MLAU244146565', 'MLAU244146565', 'Retinol puro y gradual con vitamina B3. Ojo con la etiqueta: dice apto para piel sensible y lleva alcohol denat y fragancia.', 'De noche, sobre la piel seca, empezando dos veces por semana. Protector solar al día siguiente.', '2026-09-09', 5, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('826faa38-3298-5428-927d-639265ebb5e6', 'Dermaglós Serum Facial Niacinamida X 30 Ml Todo Tipo De Piel Día-noche', 'Dermaglós', 'serum_activo', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['manchas', 'deshidratacion', 'acne'], 'nacional', false, 1, null, 'https://http2.mlstatic.com/D_Q_NP_2X_955155-MLA92846373437_092025-V.webp', 'https://meli.la/2kjU9Yg', 'https://www.mercadolibre.com.ar/up/MLAU209241342', 'MLAU209241342', 'Niacinamida con zinc, fórmula corta y precio accesible. La niacinamida es el activo que mejor se lleva con todo lo demás.', 'Mañana y noche, después de limpiar y antes de la crema.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('31342eb5-4fb3-5bb8-949f-68065a203409', 'Detenage N 10% Niacinamida Serum Facial Antiedad 30ml', 'Detenage', 'serum_activo', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['manchas', 'deshidratacion'], 'nacional', true, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_835309-MLA92899429775_092025-V.webp', 'https://meli.la/1Sgtcvw', 'https://www.mercadolibre.com.ar/up/MLAU1655818860', 'MLAU1655818860', 'Niacinamida al 10% con hialurónico de dos pesos. Arriba de 5% no hay más beneficio demostrado, pero se tolera bien.', 'Mañana y noche, después de limpiar. Si te da calor en la cara, bajá a una vez por día.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('4bc1f9e9-cd68-5e76-9a87-6187919f6287', 'Eximia Hyalu-n Concentre X 15 Ml Tipo de piel Todo tipo de piel', 'Eximia', 'serum_activo', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['manchas', 'deshidratacion', 'textura'], 'nacional', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_890166-MLA107580347157_022026-V.webp', 'https://meli.la/26Y4Xsf', 'https://www.mercadolibre.com.ar/p/MLA29882074', 'MLA29882074', 'Se vende como sérum de niacinamida y además trae tranexámico y un complejo de AHA. Exfolia más de lo que parece.', 'De noche. No lo uses la misma noche que otro exfoliante ni que un retinoide.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('f9972d79-114b-5a31-b8e5-3b4b3ab140a6', 'La Roche Posay Pure Vitamin C12 Serum', 'La Roche-Posay', 'serum_activo', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['manchas', 'acne', 'textura', 'deshidratacion'], 'europeo', false, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_707825-MLA82842096650_032025-V.webp', 'https://meli.la/1XJg8Nt', 'https://www.mercadolibre.com.ar/p/MLA47223033', 'MLA47223033', 'Vitamina C pura al 12%, la forma con más evidencia. Trae además ácido salicílico, que no es lo que uno espera en un sérum de C.', 'A la mañana, antes del protector. Si el líquido vira a naranja se oxidó: ahí ya no sirve.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('f97e6ed9-4133-50a5-b4fe-4f5780557aab', 'Liftactiv Supreme Vitamina C Serum 20ml Vichy', 'Vichy', 'serum_activo', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['manchas', 'deshidratacion'], 'europeo', false, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_633276-MLA84845473977_052025-V.webp', 'https://meli.la/2FSEDu1', 'https://www.mercadolibre.com.ar/p/MLA19710676', 'MLA19710676', 'Vitamina C pura al 16% con vitamina E, que la estabiliza y la potencia.', 'A la mañana, antes del protector solar. Guardala lejos de la luz.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('e7bb0026-7146-514d-8ac0-056f82a5f465', 'Sérum Anti-imperfecciones con Ácido Salicílico de Garnier 30ml', 'Garnier', 'serum_activo', 0, 'ambos', array['grasa', 'mixta', 'normal'], array['manchas', 'deshidratacion', 'acne', 'textura'], 'europeo', false, 1, null, 'https://http2.mlstatic.com/D_Q_NP_2X_866637-MLA104009607205_012026-V.webp', 'https://meli.la/1k8SB8y', 'https://www.mercadolibre.com.ar/p/MLA22843182', 'MLA22843182', 'Apila salicílico, láctico, fítico y niacinamida. Es el producto con más activos por mililitro del catálogo, y eso corta para los dos lados.', 'De noche, empezando día por medio. No lo combines con otro exfoliante.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('72651e35-bd63-5f51-880b-30cbc19cb5c4', 'Sérum Brightening Kosmos Vitamina C Pura', 'Kosmos', 'serum_activo', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['manchas', 'deshidratacion'], 'nacional', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_780709-MLA110294795408_052026-V.webp', 'https://meli.la/2tUhzCr', 'https://www.mercadolibre.com.ar/p/MLA45672941', 'MLA45672941', 'Repite el trío con más respaldo que existe —vitamina C pura, vitamina E y ácido ferúlico— y suma ceramidas.', 'A la mañana, antes del protector. Si el color vira a naranja, descartala.', '2026-09-09', 5, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('bd3180fa-aaaf-5bf7-a6ac-dd0e6cfd92da', 'Sérum La Roche-Posay Mela B3 Antimanchas con Niacinamida 30ml', 'La Roche-Posay', 'serum_activo', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['manchas', 'deshidratacion', 'textura', 'acne'], 'europeo', false, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_843603-MLA115081052081_072026-V.webp', 'https://meli.la/2ja226e', 'https://www.mercadolibre.com.ar/p/MLA34459961', 'MLA34459961', 'Melasyl trabaja el pigmento por una vía distinta de la habitual: en vez de frenar la enzima, atrapa el precursor. Tiene un ensayo contra hidroquinona al 4%.', 'Mañana y noche, después de limpiar. Trae retinil palmitato: si ya usás un retinoide, estás usando dos.', '2026-09-09', 5, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('ecd8932e-d99a-5c53-ad94-edcbeba21fb4', 'Sérum La Roche-Posay Mela B3 Antimanchas con Niacinamida 30ml Opcion 2', 'La Roche-Posay', 'serum_activo', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['manchas', 'deshidratacion', 'textura', 'acne'], 'europeo', false, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_938266-MLU73805693613_012024-V.webp', 'https://meli.la/2rXvDa4', 'https://www.mercadolibre.com.ar/p/MLA26197969', 'MLA26197969', 'Melasyl trabaja el pigmento por una vía distinta de la habitual: en vez de frenar la enzima, atrapa el precursor. Tiene un ensayo contra hidroquinona al 4%.', 'Mañana y noche, después de limpiar. Trae retinil palmitato: si ya usás un retinoide, estás usando dos.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('f0b2811c-90dc-544d-b3db-3d7711faf69f', 'Skinceuticals C E Ferulic Sérum De Ácido Ferúlico 30ml Todo Tipo De Piel Día-noche', 'SkinCeuticals', 'serum_activo', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['manchas', 'deshidratacion'], 'europeo', false, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_910826-MLU70654717978_072023-V.webp', 'https://meli.la/1V91gHN', 'https://www.mercadolibre.com.ar/p/MLA24840827', 'MLA24840827', 'Es, literalmente, la fórmula del estudio: 15% de vitamina C pura, 1% de vitamina E y 0,5% de ácido ferúlico. Doce ingredientes y sin fragancia.', 'A la mañana, sobre la piel limpia y seca, antes del protector. Cuatro o cinco gotas alcanzan.', '2026-09-09', 5, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('04b77f59-3bf6-5b04-9a5e-e7662616f848', 'Celimax The Real Noni Energy Ampoule Serum', 'Celimax', 'serum_secundario', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['deshidratacion'], 'coreano', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_667599-MLA111827863539_052026-V.webp', 'https://meli.la/2ZZeJju', 'https://www.mercadolibre.com.ar/p/MLA45338822', 'MLA45338822', 'Casi tres cuartos de extracto de noni, con ceramidas, escualano y colesterol. Trabaja la barrera más que una preocupación puntual.', 'De noche, después del sérum. Trae aceite esencial de romero: si tu piel reacciona, salteala.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('dd122b0b-ead4-5bef-a516-ce238f45ae57', 'Eximia Hyalu B Concentré Serum Antiedad X 30ml', 'Eximia', 'serum_secundario', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['deshidratacion', 'manchas', 'acne'], 'nacional', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_699471-MLA97504678238_112025-V.webp', 'https://meli.la/1KU9QZY', 'https://www.mercadolibre.com.ar/p/MLA45991792', 'MLA45991792', 'Hialurónico con pantenol y niacinamida. Trae cobre, que conviene no cruzar con vitamina C pura en la misma aplicación.', 'De noche, si de mañana usás vitamina C. Después de limpiar y antes de la crema.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('0547f1a8-4a58-521a-8f70-b5d8621b4a1d', 'La Roche-Posay Hyalu B5 Suractivated Serum 30 Ml', 'La Roche-Posay', 'serum_secundario', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['deshidratacion'], 'europeo', false, 3, null, 'https://http2.mlstatic.com/D_Q_NP_2X_762617-MLA94808075909_102025-V.webp', 'https://meli.la/2pSRQ1q', 'https://www.mercadolibre.com.ar/p/MLA59802317', 'MLA59802317', 'Cuatro tipos de hialurónico con pantenol y madecasósido, que es el componente de centella con más respaldo propio.', 'Mañana y noche, sobre la piel todavía húmeda, y sellá con crema encima.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('5603d4f7-3e32-586b-8655-8e6acffe2468', 'Sérum Ácido Hialurónico Vichy Minéral 89 Booster Hidratante Gel 50ml', 'Vichy', 'serum_secundario', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['deshidratacion'], 'europeo', true, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_775175-MLA96793754830_112025-V.webp', 'https://meli.la/2iXjeCp', 'https://www.mercadolibre.com.ar/p/MLA18964459', 'MLA18964459', 'Lista corta, sin fragancia y sin activos fuertes: es el que se puede sumar a cualquier rutina sin recalcular nada.', 'Mañana y noche, sobre la piel húmeda, antes de la crema.', '2026-09-09', 4, true, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('914fa2b9-679c-50cb-a01e-e7713bfcbba3', 'Serum Hidratante Concentrado Neutrogena® Hydro Boost 30 Ml', 'Neutrogena', 'serum_secundario', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca'], array['deshidratacion'], 'europeo', false, 1, null, 'https://http2.mlstatic.com/D_Q_NP_2X_703489-MLU72748302713_112023-V.webp', 'https://meli.la/17ssJ5t', 'https://www.mercadolibre.com.ar/p/MLA22655637', 'MLA22655637', 'Hialurónico concentrado y poco más. Cuando la rutina ya tiene activos, este es el paso que suma agua sin sumar problemas.', 'Mañana y noche sobre la piel húmeda. Sellalo con crema: si no, en ambiente seco puede jugarte en contra.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('ace75d88-f5d6-5ec8-9ec2-02fe2525dc3b', 'Sérum Rostro Revitalift Ácido Hialurónico L''Oréal Paris 30ml', null, 'serum_secundario', 0, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['deshidratacion', 'manchas'], 'europeo', true, 1, null, 'https://http2.mlstatic.com/D_Q_NP_2X_600230-MLU72273908364_102023-V.webp', 'https://meli.la/2af2zRS', 'https://www.mercadolibre.com.ar/p/MLA18956615', 'MLA18956615', 'Hialurónico con un derivado de vitamina C, que es la versión estable y sin ardor de la vitamina C.', 'Mañana y noche, después de limpiar.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('2fc14288-5884-5849-ba10-f35d48b14a74', 'Skin1004 Ampolla Serum Anti-acné Tea-trica Relief', 'Skin1004', 'serum_secundario', 0, 'ambos', array['grasa', 'mixta', 'normal'], array['deshidratacion', 'acne'], 'coreano', false, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_621082-MLA77817756654_072024-V.webp', 'https://meli.la/2xDfY4m', 'https://www.mercadolibre.com.ar/p/MLA38719413', 'MLA38719413', 'Centella con árbol de té, orientada a piel que hace granitos. El árbol de té tiene evidencia razonable, pero sigue siendo un aceite esencial.', 'De noche, después de limpiar. Si tu piel reacciona fácil, probala primero en una zona chica.', '2026-09-09', 4, false, false)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, relevado, prioridad, comodin, activo)
values ('c88d5ad8-e7da-51ac-96c9-0f015dddfed2', 'Skin1004 Poremizing Fresh Ampoule', 'Skin1004', 'serum_secundario', 0, 'ambos', array['grasa', 'mixta', 'normal', 'sensible'], array['deshidratacion'], 'coreano', true, 2, null, 'https://http2.mlstatic.com/D_Q_NP_2X_739679-MLA80426317912_112024-V.webp', 'https://meli.la/1kRJsbt', 'https://www.mercadolibre.com.ar/p/MLA43183566', 'MLA43183566', 'Ampolla liviana con centella y péptidos, orientada a la apariencia del poro. Trae cobre, así que mejor no cruzarla con vitamina C pura.', 'De noche, si de mañana usás vitamina C. Sobre la piel limpia.', '2026-09-09', 3, false, false)
on conflict (id) do nothing;
