-- Seed de 24 productos de ejemplo. Generado por scripts/gen-seed.ts.
-- No editar a mano: cambiá src/niches/skincare/productos.ts y corré npm run gen-seed.

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('5d221906-39be-54cf-8a4b-a8451c1bc147', 'Espuma Facial Extra Suave Mousse Cleanser', 'Idraet', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['textura', 'deshidratacion'], 'nacional', true, 1, 23200, 'https://http2.mlstatic.com/D_Q_NP_2X_832048-MLA104005799796_012026-V.webp', 'https://meli.la/11EmxSu', 'https://www.mercadolibre.com.ar/p/MLA21801426', 'MLA21801426', 'Mousse de limpieza suave: saca la mugre del día sin dejar la piel tirante.', 'Mañana y noche, sobre la cara húmeda.', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('177a52d8-37db-52eb-91a0-588b515f3170', 'Gel Limpiador Facial Espumoso 236 ml', 'CeraVe', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'normal'], array['acne', 'textura'], 'europeo', true, 3, 55620, 'https://http2.mlstatic.com/D_Q_NP_2X_831598-MLA48269275817_112021-V.webp', 'https://meli.la/2Y8r46h', 'https://www.mercadolibre.com.ar/p/MLAU140993030', 'MLAU140993030', 'Gel espumoso para piel grasa o mixta, con ceramidas para no romper la barrera.', 'Mañana y noche. Si te reseca, dejalo solo de noche.', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('df632bf0-55e0-5fa8-8515-a863341156e3', 'Low pH Good Morning Gel Cleanser 150 ml', 'COSRX', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'textura', 'deshidratacion'], 'coreano', true, 2, 37504, 'https://http2.mlstatic.com/D_Q_NP_2X_865672-MLU75328154403_032024-V.webp', 'https://meli.la/2m5jdnL', 'https://www.mercadolibre.com.ar/p/MLA11139349', 'MLA11139349', 'Limpiador de pH bajo: respeta el manto ácido de la piel, por eso cae bien a la mañana.', 'Mañana y noche sobre la cara húmeda, poca cantidad.', 3, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('9f11e96c-a0d6-595c-836b-e2b01e5777d3', 'Centella Cleansing Foam 150 ml', 'Mixsoon', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'textura', 'deshidratacion'], 'coreano', true, 2, 38399, 'https://http2.mlstatic.com/D_Q_NP_2X_838019-MLA93483193946_102025-V.webp', 'https://meli.la/2s4tZod', 'https://www.mercadolibre.com.ar/p/MLAU3453545171', 'MLAU3453545171', 'Espuma con centella, pensada para limpiar sin dejar la piel chirriando.', 'Mañana y noche sobre la cara húmeda.', 3, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('b944b75b-d195-5887-8c4a-ec6997fd2679', 'Centella Ampoule Foam 125 ml', 'Skin1004', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'textura', 'deshidratacion'], 'coreano', true, 2, 36719, 'https://http2.mlstatic.com/D_Q_NP_2X_743990-MLA108176636618_032026-V.webp', 'https://meli.la/1sdkRtd', 'https://www.mercadolibre.com.ar/p/MLAU3856054670', 'MLAU3856054670', 'Espuma de centella asiática. Limpia parejo y le va bien a casi cualquier piel.', 'Mañana y noche sobre la cara húmeda, enjuagá con agua.', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('5287ad8a-fb88-5094-a48f-51c710cd96ce', 'Cleanex Free Gel Limpiador 150 g', 'Cleanex', 'limpiador', 2, 'ambos', array['grasa', 'mixta', 'sensible'], array['acne', 'textura'], 'nacional', true, 2, 40162, 'https://http2.mlstatic.com/D_Q_NP_2X_716982-MLU72122769372_102023-V.webp', 'https://meli.la/1sBpdZ3', 'https://www.mercadolibre.com.ar/p/MLA27603374', 'MLA27603374', 'Gel de limpieza sin jabón, formulado para piel sensible que además hace grasitud.', 'Mañana y noche. Enjuagá bien.', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('faafd241-6fe8-56a8-a766-ccdb6164db56', 'Ginseng Cleansing Oil Desmaquillante', 'Beauty of Joseon', 'limpiador_oleoso', 1, 'pm', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'textura', 'deshidratacion'], 'coreano', true, 2, 54739, 'https://http2.mlstatic.com/D_Q_NP_2X_965384-MLU78057625931_072024-V.webp', 'https://meli.la/1yridAk', 'https://www.mercadolibre.com.ar/p/MLA37240248', 'MLA37240248', 'Primer paso de la doble limpieza: el aceite saca protector solar y maquillaje que el agua sola no levanta.', 'De noche, sobre la cara SECA. Masajeá, mojate las manos para emulsionar y enjuagá. Después va el limpiador.', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('1f69f11c-96bc-5e0d-b79b-684a56278a28', 'Revitalift Glass Skin Crema 50 g', 'L''Oreal Paris', 'hidratante', 7, 'ambos', array['mixta', 'normal', 'seca'], array['textura', 'deshidratacion'], 'europeo', false, 2, 46477, 'https://http2.mlstatic.com/D_Q_NP_2X_678886-MLA106918493109_022026-V.webp', 'https://meli.la/2hbp4z9', 'https://www.mercadolibre.com.ar/p/MLA65451035', 'MLA65451035', 'Hidratante de textura liviana que deja la piel con aspecto pulido.', 'Después de limpiar, mañana y noche.', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('599f5ffc-515b-53e3-b1a9-6fa7f105cc0c', 'Tea-trica B5 Crema Facial 75 ml', 'Skin1004', 'hidratante', 7, 'ambos', array['grasa', 'mixta'], array['acne', 'textura'], 'coreano', true, 2, 45475, 'https://http2.mlstatic.com/D_Q_NP_2X_994827-MLU76998762803_062024-V.webp', 'https://meli.la/2HagYva', 'https://www.mercadolibre.com.ar/p/MLA37722163', 'MLA37722163', 'Hidratante con B5 pensada para piel oleosa y acneica: hidrata sin sensación pesada.', 'Después de limpiar, mañana y noche.', 5, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('6b7300c1-a37c-5810-a06b-a114171cc45f', 'Toleriane Dermallergo Crema 40 ml', 'La Roche-Posay', 'hidratante', 7, 'ambos', array['seca', 'sensible'], array['deshidratacion', 'textura'], 'europeo', true, 3, 114414, 'https://http2.mlstatic.com/D_Q_NP_2X_785042-MLU75601430788_042024-V.webp', 'https://meli.la/1gTzEb6', 'https://www.mercadolibre.com.ar/p/MLA19866311', 'MLA19866311', 'Formulada para piel reactiva: mínimo de ingredientes, sin fragancia.', 'Después de limpiar, mañana y noche.', 5, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('0385d1a3-9ab2-5343-9184-2abbd7a5502e', 'Dynasty Cream 50 ml', 'Beauty of Joseon', 'hidratante', 7, 'ambos', array['normal', 'seca'], array['deshidratacion', 'textura'], 'coreano', true, 3, 77299, 'https://http2.mlstatic.com/D_Q_NP_2X_914805-MLU75324226927_032024-V.webp', 'https://meli.la/1knxxHr', 'https://www.mercadolibre.com.ar/p/MLA21179266', 'MLA21179266', 'Crema nutritiva para piel que tira. Más rica que una gel-crema.', 'Después de limpiar, mañana y noche.', 5, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('cae68c7d-d0d5-569c-97c1-dc7685e0fc83', 'Hyaluronic 4D Face Cream', 'Lidherma', 'hidratante', 7, 'ambos', array['mixta', 'normal', 'seca'], array['deshidratacion'], 'nacional', true, 1, 31573, 'https://http2.mlstatic.com/D_Q_NP_2X_751116-MLA51443088672_092022-V.webp', 'https://meli.la/2KUmRn1', 'https://www.mercadolibre.com.ar/p/MLA19474747', 'MLA19474747', 'Hidratación con hialurónico a precio nacional. Textura liviana.', 'Después de limpiar, mañana y noche.', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('fb6c8719-ae28-51c3-a2b7-185729019a95', 'Advanced Snail All In One Cream 50 ml', 'COSRX', 'hidratante', 7, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'manchas', 'textura', 'deshidratacion'], 'coreano', true, 1, 32999, 'https://http2.mlstatic.com/D_Q_NP_2X_843019-MLA115354367281_072026-V.webp', 'https://meli.la/1VZ7wAp', 'https://www.mercadolibre.com.ar/p/MLA45253335', 'MLA45253335', 'Mucina de caracol: hidrata y ayuda a que las marcas se vayan emparejando. Muy versátil.', 'Después de limpiar, mañana y noche.', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('3043ace8-c198-5554-a4ef-4b3e0248ff31', 'Crema Hidratante de Dia FPS 30 50 g', 'Dermaglos', 'hidratante', 7, 'am', array['mixta', 'normal', 'seca'], array['deshidratacion'], 'nacional', false, 1, 32661, 'https://http2.mlstatic.com/D_Q_NP_2X_695563-MLU72756171168_112023-V.webp', 'https://meli.la/2kbgQEt', 'https://www.mercadolibre.com.ar/p/MLA24692733', 'MLA24692733', 'Hidratante con FPS 30 incorporado. Resuelve dos pasos si vas corriendo.', 'A la mañana. Si vas a estar al sol, sumale un protector aparte.', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('ef88803e-f240-5ac9-a0c7-6dc45023f5cb', 'Protector Solar Rice + Probioticos SPF50+', 'Beauty of Joseon', 'protector_solar', 8, 'am', array['mixta', 'normal', 'seca', 'sensible'], array['manchas', 'textura', 'deshidratacion'], 'coreano', true, 2, 51999, 'https://http2.mlstatic.com/D_Q_NP_2X_957567-MLA94539763645_102025-V.webp', 'https://meli.la/1B2LZaE', 'https://www.mercadolibre.com.ar/p/MLAU3480823224', 'MLAU3480823224', 'Filtro coreano de textura liviana, no deja blanco ni sensación pegajosa.', 'Último paso de la mañana, todos los días.', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('2b09ab2e-48f4-5490-860e-b01d8e980e4f', 'Fusion Water Magic SPF 50', 'ISDIN', 'protector_solar', 8, 'am', array['grasa', 'mixta', 'normal'], array['acne', 'manchas'], 'europeo', false, 3, 55904, 'https://http2.mlstatic.com/D_Q_NP_2X_711953-MLA99930410153_112025-V.webp', 'https://meli.la/2SdyX9m', 'https://www.mercadolibre.com.ar/p/MLA26916726', 'MLA26916726', 'Textura agua, se absorbe rápido. Un clásico para piel que brilla.', 'Último paso de la mañana. Reponé cada 3-4 hs si estás al sol.', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('243c3ca9-7456-5c5f-adae-56bc432fdc4c', 'Ultra-light Invisible Sunscreen SPF 50 PA++++ 50 ml', 'COSRX', 'protector_solar', 8, 'am', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'manchas', 'textura', 'deshidratacion'], 'coreano', true, 2, 42299, 'https://http2.mlstatic.com/D_Q_NP_2X_729825-MLA107254048819_022026-V.webp', 'https://meli.la/1mZvXGj', 'https://www.mercadolibre.com.ar/p/MLA2097460920', 'MLA2097460920', 'Muy liviano e invisible. Es el más fácil de usar todos los días sin renegar.', 'Último paso de la mañana, todos los días.', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('ee65576a-883b-5b68-82d9-b06c4540f9cc', 'Sun Oil Control Toque Seco FPS 50 50 ml', 'Eucerin', 'protector_solar', 8, 'am', array['grasa', 'mixta'], array['acne'], 'europeo', false, 2, 53206, 'https://http2.mlstatic.com/D_Q_NP_2X_967739-MLA117137014457_092026-V.webp', 'https://meli.la/1j7eFWb', 'https://www.mercadolibre.com.ar/p/MLA16048275', 'MLA16048275', 'Acabado seco de verdad: control de brillo para piel muy oleosa.', 'Último paso de la mañana.', 5, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('49a08f9d-4ffe-54a6-ae25-cb54ece5198f', 'Hyalu-Cica Water-Fit Sun Serum SPF50+ 50 ml', 'Skin1004', 'protector_solar', 8, 'am', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'textura', 'deshidratacion'], 'coreano', true, 2, 54000, 'https://http2.mlstatic.com/D_Q_NP_2X_614355-MLA99834144935_112025-V.webp', 'https://meli.la/2ME4rDC', 'https://www.mercadolibre.com.ar/p/MLA24454808', 'MLA24454808', 'Protector con textura de serum. Se siente como un paso de skincare, no como pantalla solar.', 'Último paso de la mañana, todos los días.', 3, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('1782a74e-046f-572d-b361-27dacdf2b3ea', 'Fusion Water Magic Color Light SPF 50 50 ml', 'ISDIN', 'protector_solar', 8, 'am', array['grasa', 'mixta', 'normal'], array['manchas', 'textura'], 'europeo', false, 2, 52980, 'https://http2.mlstatic.com/D_Q_NP_2X_611145-MLA99918803569_112025-V.webp', 'https://meli.la/1YCbeGw', 'https://www.mercadolibre.com.ar/p/MLA20067103', 'MLA20067103', 'Igual que el Fusion Water pero con color: empareja el tono y reemplaza la base liviana.', 'Último paso de la mañana.', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('5540f526-7bbb-587e-9340-4c367d3fecb5', 'Protector Solar Facial Control Anti-Brillo FPS 50 50 ml', 'NIVEA', 'protector_solar', 8, 'am', array['grasa', 'mixta'], array['acne'], 'europeo', false, 1, 15488, 'https://http2.mlstatic.com/D_Q_NP_2X_788259-MLA117198265649_092026-V.webp', 'https://meli.la/2DuYPWN', 'https://www.mercadolibre.com.ar/p/MLA16189493', 'MLA16189493', 'La opción más barata de la lista para cumplir con el paso que más importa.', 'Último paso de la mañana, todos los días.', 5, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('eca1e945-2ceb-5a4b-8d53-5afe77870730', 'Serum Anti Manchas Vitamina C 30 ml', 'Garnier', 'serum_activo', 4, 'am', array['grasa', 'mixta', 'normal', 'seca'], array['manchas', 'textura'], 'europeo', false, 1, 24693, 'https://http2.mlstatic.com/D_Q_NP_2X_984767-MLA114537078502_082026-V.webp', 'https://meli.la/2cvShSS', 'https://www.mercadolibre.com.ar/p/MLA18957818', 'MLA18957818', 'Vitamina C accesible para trabajar sobre manchas y marcas.', 'A la mañana, antes del protector. Empezá día por medio.', 4, false, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('2e00ac05-c649-5f6d-bfd2-cce864f2e80e', 'Niacinamida 10% + Zinc 1% 30 ml', 'The Ordinary', 'serum_activo', 4, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['acne', 'manchas', 'textura'], 'europeo', true, 2, 39999, 'https://http2.mlstatic.com/D_Q_NP_2X_670477-MLU69223240175_052023-V.webp', 'https://meli.la/1Fophba', 'https://www.mercadolibre.com.ar/p/MLA23033385', 'MLA23033385', 'Equilibra el brillo y ayuda con poros y marcas. El activo más fácil para arrancar.', 'Unas gotas antes de la crema, mañana o noche.', 3, true, true)
on conflict (id) do nothing;

insert into productos (id, nombre, marca, categoria, paso, momento, tipos_piel, preocupaciones, origen, apto_sensible, rango_precio, precio_ars, imagen_url, link_afiliado, url_referencia, ml_id, por_que, como_usar, prioridad, comodin, activo)
values ('9f280ac4-84cb-5eca-b3cd-583eceef3219', 'Mineral 89 Contorno de Ojos 15 ml', 'Vichy', 'contorno', 6, 'ambos', array['grasa', 'mixta', 'normal', 'seca', 'sensible'], array['deshidratacion', 'textura'], 'europeo', true, 2, 47977, 'https://http2.mlstatic.com/D_Q_NP_2X_623415-MLU78028761401_072024-V.webp', 'https://meli.la/1d7iet1', 'https://www.mercadolibre.com.ar/p/MLA18956630', 'MLA18956630', 'Contorno liviano con ácido hialurónico. Apto para todo tipo de piel.', 'Golpecitos suaves alrededor del ojo, mañana y noche.', 3, true, true)
on conflict (id) do nothing;
