import type { Producto } from "@/engine/recomendacion";

// ─────────────────────────────────────────────────────────────────────────────
// CATÁLOGO — fuente de verdad. Acá pegás los links de afiliado hechos a mano.
//
// FLUJO:
//   1. Generás el link de afiliado a mano en Mercado Libre.
//   2. Lo pegás en `link_afiliado` del producto.
//   3. `npm run sync`   → sube este archivo a Supabase (y desactiva lo que sacaste).
//   4. `npm run cobertura` → te dice qué combinaciones todavía caen a un comodín,
//      para saber dónde conviene cargar el próximo link.
//
// REGLAS:
//   - Al menos un producto con `comodin: true` por cada categoría que use la rutina
//     (limpiador, hidratante, protector_solar, serum, exfoliante). Es lo que
//     garantiza que ningún paso quede vacío.
//   - `tipos_piel` y `preocupaciones` son arrays: un mismo producto cubre varias combos.
//   - `rango_precio`: 1 = económico · 2 = medio · 3 = premium.
//
// Estos 12 son de ejemplo, con links PLACEHOLDER. Reemplazá cada `link_afiliado`.
// ─────────────────────────────────────────────────────────────────────────────

const LINK_PLACEHOLDER = "https://www.mercadolibre.com.ar/#REEMPLAZAR-LINK-AFILIADO";

export const productos: Producto[] = [
  // ── Comodines (blindan cada categoría) ──────────────────────────────────────
  {
    id: "00000000-0000-4000-8000-000000000001",
    nombre: "Espuma limpiadora",
    marca: "CeraVe",
    categoria: "limpiador",
    paso: 1,
    momento: "ambos",
    tipos_piel: ["grasa", "mixta", "seca", "sensible"],
    preocupaciones: ["acne", "manchas", "textura", "deshidratacion"],
    rango_precio: 1,
    precio_ars: 8900,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Limpia sin resecar y le va bien a casi cualquier piel.",
    como_usar: "Mañana y noche, sobre la cara húmeda, enjuagá con agua.",
    prioridad: 1,
    comodin: true,
    activo: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    nombre: "Crema hidratante",
    marca: "CeraVe",
    categoria: "hidratante",
    paso: 3,
    momento: "ambos",
    tipos_piel: ["grasa", "mixta", "seca", "sensible"],
    preocupaciones: ["acne", "manchas", "textura", "deshidratacion"],
    rango_precio: 1,
    precio_ars: 12500,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Hidrata parejo y no deja sensación pesada.",
    como_usar: "Después de limpiar, mañana y noche.",
    prioridad: 1,
    comodin: true,
    activo: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    nombre: "Fusion Water FPS 50",
    marca: "ISDIN",
    categoria: "protector_solar",
    paso: 5,
    momento: "am",
    tipos_piel: ["grasa", "mixta", "seca", "sensible"],
    preocupaciones: ["acne", "manchas", "textura", "deshidratacion"],
    rango_precio: 2,
    precio_ars: 24000,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Textura súper liviana, se absorbe rápido y no deja blanco.",
    como_usar: "Último paso de la mañana, todos los días. Reponé cada 3-4 hs.",
    prioridad: 1,
    comodin: true,
    activo: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    nombre: "Niacinamide 10% + Zinc 1%",
    marca: "The Ordinary",
    categoria: "serum",
    paso: 2,
    momento: "ambos",
    tipos_piel: ["grasa", "mixta", "seca", "sensible"],
    preocupaciones: ["acne", "manchas", "textura", "deshidratacion"],
    rango_precio: 1,
    precio_ars: 9500,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Equilibra el brillo y ayuda con poros y marcas. Muy versátil.",
    como_usar: "Unas gotas antes de la crema, mañana o noche.",
    prioridad: 1,
    comodin: true,
    activo: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000005",
    nombre: "Lactic Acid 5% + HA",
    marca: "The Ordinary",
    categoria: "exfoliante",
    paso: 4,
    momento: "pm",
    tipos_piel: ["grasa", "mixta", "seca"],
    preocupaciones: ["textura", "manchas"],
    rango_precio: 1,
    precio_ars: 11000,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Exfoliación suave que empareja la textura sin ser agresiva.",
    como_usar: "De noche, 2-3 veces por semana. No mezclar con otros ácidos.",
    prioridad: 1,
    comodin: true,
    activo: true,
  },

  // ── Estrellas (mejor match para combos frecuentes) ─────────────────────────
  {
    id: "00000000-0000-4000-8000-000000000006",
    nombre: "Effaclar Gel",
    marca: "La Roche-Posay",
    categoria: "limpiador",
    paso: 1,
    momento: "ambos",
    tipos_piel: ["grasa", "mixta"],
    preocupaciones: ["acne", "textura"],
    rango_precio: 2,
    precio_ars: 18000,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Pensado para piel grasa con tendencia a granitos.",
    como_usar: "Mañana y noche sobre la cara húmeda.",
    prioridad: 5,
    comodin: false,
    activo: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000007",
    nombre: "Vitamina C 10%",
    marca: "La Roche-Posay",
    categoria: "serum",
    paso: 2,
    momento: "ambos",
    tipos_piel: ["grasa", "mixta", "seca"],
    preocupaciones: ["manchas", "textura"],
    rango_precio: 3,
    precio_ars: 42000,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Ilumina y ayuda a emparejar manchas con el tiempo.",
    como_usar: "A la mañana, antes del protector.",
    prioridad: 5,
    comodin: false,
    activo: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000008",
    nombre: "Crema para piel seca",
    marca: "CeraVe",
    categoria: "hidratante",
    paso: 3,
    momento: "ambos",
    tipos_piel: ["seca", "sensible"],
    preocupaciones: ["deshidratacion"],
    rango_precio: 1,
    precio_ars: 9900,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Más rica en emolientes para pieles que tiran.",
    como_usar: "Después de limpiar, mañana y noche.",
    prioridad: 4,
    comodin: false,
    activo: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000009",
    nombre: "Ácido Hialurónico 2%",
    marca: "The Ordinary",
    categoria: "serum",
    paso: 2,
    momento: "ambos",
    tipos_piel: ["grasa", "mixta", "seca", "sensible"],
    preocupaciones: ["deshidratacion"],
    rango_precio: 1,
    precio_ars: 8500,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Suma hidratación sin peso, ideal si la piel tira.",
    como_usar: "Sobre la piel apenas húmeda, antes de la crema.",
    prioridad: 4,
    comodin: false,
    activo: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000010",
    nombre: "Fusion Water Oil Control FPS 50",
    marca: "ISDIN",
    categoria: "protector_solar",
    paso: 5,
    momento: "am",
    tipos_piel: ["grasa", "mixta"],
    preocupaciones: ["acne", "textura"],
    rango_precio: 2,
    precio_ars: 25000,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Control de brillo para piel grasa, acabado seco.",
    como_usar: "Último paso de la mañana, todos los días.",
    prioridad: 4,
    comodin: false,
    activo: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000011",
    nombre: "Salicylic Acid 2%",
    marca: "The Ordinary",
    categoria: "exfoliante",
    paso: 4,
    momento: "pm",
    tipos_piel: ["grasa", "mixta"],
    preocupaciones: ["acne", "textura"],
    rango_precio: 2,
    precio_ars: 16000,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Destapa poros y ayuda con los granitos.",
    como_usar: "De noche, empezá 2 veces por semana.",
    prioridad: 5,
    comodin: false,
    activo: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000012",
    nombre: "Loción hidratante",
    marca: "Cetaphil",
    categoria: "hidratante",
    paso: 3,
    momento: "ambos",
    tipos_piel: ["sensible", "seca"],
    preocupaciones: ["deshidratacion", "textura"],
    rango_precio: 2,
    precio_ars: 17000,
    link_afiliado: LINK_PLACEHOLDER,
    por_que: "Suave para piel sensible, sin fragancia.",
    como_usar: "Después de limpiar, mañana y noche.",
    prioridad: 4,
    comodin: false,
    activo: true,
  },
];
